from django.urls import path
from .views import (
    home,
    pool_list,
    pool_detail,
    pool_service_details,
    pool_issue_create,
    pool_issue_update,
    water_reading_create,
    water_object_visit_create,
    water_reading_edit,
    readings_all,
    task_create,
    task_edit,
    task_delete,
    task_move,
    visit_plan_move,
    profile_view,
    users_view,
    billing_info,
    billing_request,
    billing_admin,
    clients_list,
    crm_index,
    crm_tasks,
    crm_tasks_bulk_update,
    crm_list,
    crm_bulk_update,
    archive_list,
    archive_restore_task,
    archive_restore_crm_item,
    archive_bulk_update,
    archive_delete_task_forever,
    archive_delete_crm_item_forever,
    crm_create,
    crm_view,
    crm_edit,
    crm_issue_photo_download,
    crm_issue_primary_photo_download,
    register,
    pool_create,
    pool_delete,
    pool_edit,
    pool_restore,
    client_create,
    client_edit,
    client_delete,
    yandex_suggest,
    confirm_email,
    resend_email_confirmation,
    confirm_phone,
    password_change_inline,
    signup_personal,
    signup_company,
    notifications_list,
    notification_mark_read,
    notification_push_open,
    notification_push_open_token,
    notifications_mark_all,
    notifications_resolve_all,
    notification_resolve,
    organization_norms,
    invite_create,
    invite_resend,
    invite_accept,
    invite_delete,
    client_staff,
    client_invite_create,
    client_invite_resend,
    client_invite_accept,
    client_invite_delete,
    client_staff_toggle_block,
    client_staff_delete,
    client_staff_change_role,
    staff_toggle_block,
    staff_delete,
    staff_change_role,
    pool_staff_change_role,
    smsru_callback,
    push_subscribe,
    push_unsubscribe,
)
from . import views
from .security_views import (
    security_lock,
    security_pin_disable,
    security_pin_quick_setup,
    security_pin_set,
    security_unlock,
    webauthn_authentication_options,
    webauthn_authentication_verify,
    webauthn_credential_delete,
    webauthn_prompt_dismiss,
    webauthn_registration_options,
    webauthn_registration_verify,
)
from .finance_views import (
    finance_cash_dashboard,
    finance_cash_accountable_issue_create,
    finance_cash_income_create,
    finance_cash_operation_delete,
    finance_cash_operation_detail,
    finance_cash_operation_edit,
    finance_cash_operation_review,
    finance_cash_transfer_create,
    finance_card_transfer_attachment_download,
    finance_card_transfer_create,
    finance_card_transfer_dashboard,
    finance_card_transfer_detail,
    finance_card_transfer_review,
    finance_cash_count_create,
    finance_dashboard,
    finance_company_cash_dashboard,
    finance_employee_detail,
    finance_kkm_cash_dashboard,
    finance_accountable_return_create,
    finance_income_create,
    finance_income_delete,
    finance_income_edit,
    finance_expense_create,
    finance_expense_delete,
    finance_expense_detail,
    finance_expense_edit,
    finance_expense_bulk_onec,
    finance_expense_bulk_review,
    finance_expense_review,
    finance_period_close,
    finance_period_reopen,
    finance_receipt_download,
    finance_report,
    finance_report_export,
    finance_transaction_confirm,
    finance_transaction_create,
    finance_transaction_review,
    finance_transaction_void,
    finance_onec_import_list,
    finance_onec_gross_profit_dashboard,
    finance_onec_cost_control,
    finance_onec_monthly_profit_upload,
    finance_onec_import_preview,
    finance_onec_import_confirm,
    finance_onec_import_cancel,
    finance_onec_import_detail,
)
from .development_views import (
    development_iteration_create,
    development_task_analysis_check,
    development_task_analysis_launch,
    development_task_create,
    development_task_codex_check,
    development_task_codex_start,
    development_task_detail,
    development_task_finalize_audit,
    development_task_list,
    development_task_review_resolve,
    development_task_review_resolve_unknown,
    development_task_review_retry_unknown,
    development_task_start,
    development_task_update,
)

urlpatterns = [
    path('', home, name='home'),
    path('index/', views.index, name='index'),
    path('pools/', pool_list, name='pool_list'),
    path('pools/<uuid:pool_uuid>/', pool_detail, name='pool_detail'),
    path("pools/<uuid:pool_uuid>/service-details/", pool_service_details, name="pool_service_details"),
    path("pools/<uuid:pool_uuid>/issues/new/", pool_issue_create, name="pool_issue_create"),
    path("pools/<uuid:pool_uuid>/issues/<int:item_id>/status/", pool_issue_update, name="pool_issue_update"),
    path('pools/create/', pool_create, name='pool_create'),
    path("pools/<uuid:pool_uuid>/edit/", pool_edit, name="pool_edit"),
    path("pools/<uuid:pool_uuid>/delete/", pool_delete, name="pool_delete"),
    path("pools/<uuid:pool_uuid>/restore/", pool_restore, name="pool_restore"),
    path("api/yandex/suggest/", yandex_suggest, name="yandex_suggest"),
    path('pools/<uuid:pool_uuid>/new-reading/', water_reading_create, name='water_reading_create'),
    path("objects/<uuid:pool_uuid>/new-visit/", water_object_visit_create, name="water_object_visit_create"),
    path("readings/<uuid:reading_uuid>/edit/", water_reading_edit, name="water_reading_edit"),
    path("readings/<uuid:reading_uuid>/delete/", views.water_reading_delete, name="water_reading_delete"),
    path("readings/<uuid:reading_uuid>/restore/", views.water_reading_restore, name="water_reading_restore"),
    path("readings/all", readings_all, name="readings_all"),
    path("tasks/new/", task_create, name="task_create"),
    path("tasks/<int:task_id>/", task_edit, name="task_edit"),
    path("tasks/<int:task_id>/delete/", task_delete, name="task_delete"),
    path("tasks/move/", task_move, name="task_move"),
    path("readings/plan/move/", visit_plan_move, name="visit_plan_move"),
    path("profile/", profile_view, name="profile"),
    path("security/unlock/", security_unlock, name="security_unlock"),
    path("security/lock/", security_lock, name="security_lock"),
    path("security/pin/", security_pin_set, name="security_pin_set"),
    path("security/pin/quick-setup/", security_pin_quick_setup, name="security_pin_quick_setup"),
    path("security/pin/disable/", security_pin_disable, name="security_pin_disable"),
    path("security/passkeys/register/options/", webauthn_registration_options, name="webauthn_registration_options"),
    path("security/passkeys/register/verify/", webauthn_registration_verify, name="webauthn_registration_verify"),
    path("security/passkeys/authenticate/options/", webauthn_authentication_options, name="webauthn_authentication_options"),
    path("security/passkeys/authenticate/verify/", webauthn_authentication_verify, name="webauthn_authentication_verify"),
    path("security/passkeys/prompt/dismiss/", webauthn_prompt_dismiss, name="webauthn_prompt_dismiss"),
    path("security/passkeys/<int:credential_id>/delete/", webauthn_credential_delete, name="webauthn_credential_delete"),
    path("users/", users_view, name="users"),
    path("notifications/", notifications_list, name="notifications"),
    path("notifications/<int:notification_id>/read/", notification_mark_read, name="notifications_mark_read"),
    path("notifications/<int:notification_id>/open/", notification_push_open, name="notification_push_open"),
    path("notifications/open/<str:token>/", notification_push_open_token, name="notification_push_open_token"),
    path("notifications/read-all/", notifications_mark_all, name="notifications_mark_all"),
    path("notifications/resolve-all/", notifications_resolve_all, name="notifications_resolve_all"),
    path("notifications/<int:notification_id>/resolve/", notification_resolve, name="notification_resolve"),
    path("organization/norms/", organization_norms, name="organization_norms"),
    path("users/<int:access_id>/block/", staff_toggle_block, name="staff_toggle_block"),
    path("users/<int:access_id>/delete/", staff_delete, name="staff_delete"),
    path("users/<int:access_id>/role/", staff_change_role, name="staff_change_role"),
    path("users/pool-access/<int:access_id>/role/", pool_staff_change_role, name="pool_staff_change_role"),
    path("users/invite/", invite_create, name="invite_create"),
    path("users/invite/<int:invite_id>/resend/", invite_resend, name="invite_resend"),
    path("users/invite/<int:invite_id>/delete/", invite_delete, name="invite_delete"),
    path("invite/<uuid:token>/", invite_accept, name="invite_accept"),
    path("clients/<int:client_id>/staff/", client_staff, name="client_staff"),
    path("clients/<int:client_id>/staff/invite/", client_invite_create, name="client_invite_create"),
    path("clients/<int:client_id>/staff/invite/<int:invite_id>/resend/", client_invite_resend, name="client_invite_resend"),
    path("clients/<int:client_id>/staff/invite/<int:invite_id>/delete/", client_invite_delete, name="client_invite_delete"),
    path("clients/staff/<int:access_id>/block/", client_staff_toggle_block, name="client_staff_toggle_block"),
    path("clients/staff/<int:access_id>/delete/", client_staff_delete, name="client_staff_delete"),
    path("clients/staff/<int:access_id>/role/", client_staff_change_role, name="client_staff_change_role"),
    path("client-invite/<uuid:token>/", client_invite_accept, name="client_invite_accept"),
    path("billing/", billing_info, name="billing"),
    path("billing/request/", billing_request, name="billing_request"),
    path("billing/admin/", billing_admin, name="billing_admin"),
    path("clients/", clients_list, name="clients_list"),
    path("crm/", crm_index, name="crm_index"),
    path("crm/tasks/", crm_tasks, name="crm_tasks"),
    path("crm/tasks/bulk/", crm_tasks_bulk_update, name="crm_tasks_bulk_update"),
    path("crm/photos/<int:photo_id>/", crm_issue_photo_download, name="crm_issue_photo_download"),
    path("crm/photos/item/<int:item_id>/primary/", crm_issue_primary_photo_download, name="crm_issue_primary_photo_download"),
    path("crm/<slug:direction>/", crm_list, name="crm_list"),
    path("crm/<slug:direction>/bulk/", crm_bulk_update, name="crm_bulk_update"),
    path("crm/<slug:direction>/new/", crm_create, name="crm_create"),
    path("crm/<slug:direction>/<int:item_id>/", crm_view, name="crm_view"),
    path("crm/<slug:direction>/<int:item_id>/edit/", crm_edit, name="crm_edit"),
    path("archive/", archive_list, name="archive_list"),
    path("archive/bulk/", archive_bulk_update, name="archive_bulk_update"),
    path("archive/tasks/<int:task_id>/restore/", archive_restore_task, name="archive_restore_task"),
    path("archive/tasks/<int:task_id>/delete/", archive_delete_task_forever, name="archive_delete_task_forever"),
    path("archive/crm/<int:item_id>/restore/", archive_restore_crm_item, name="archive_restore_crm_item"),
    path("archive/crm/<int:item_id>/delete/", archive_delete_crm_item_forever, name="archive_delete_crm_item_forever"),
    path("register/", register, name="register"),
    path("signup/personal/", signup_personal, name="signup_personal"),
    path("signup/company/", signup_company, name="signup_company"),
    path("accounts/confirm-email/<uidb64>/<token>/", confirm_email, name="confirm_email"),
    path("accounts/confirm-email/resend/", resend_email_confirmation, name="resend_email_confirmation"),
    path("accounts/confirm-phone/<uuid:token>/", confirm_phone, name="confirm_phone"),
    path("accounts/password-change/", password_change_inline, name="password_change_inline"),
    path("api/smsru/callback/", smsru_callback, name="smsru_callback"),
    path("api/push/subscribe/", push_subscribe, name="push_subscribe"),
    path("api/push/unsubscribe/", push_unsubscribe, name="push_unsubscribe"),
    path("finance/", finance_dashboard, name="finance_dashboard"),
    path("finance/cash/", finance_cash_dashboard, name="finance_cash_dashboard"),
    path("finance/cash/company/", finance_company_cash_dashboard, name="finance_company_cash_dashboard"),
    path("finance/cash/kkm/", finance_kkm_cash_dashboard, name="finance_kkm_cash_dashboard"),
    path("finance/card-transfers/", finance_card_transfer_dashboard, name="finance_card_transfer_dashboard"),
    path("finance/card-transfers/new/", finance_card_transfer_create, name="finance_card_transfer_create"),
    path("finance/card-transfers/<int:payment_id>/", finance_card_transfer_detail, name="finance_card_transfer_detail"),
    path("finance/card-transfers/<int:payment_id>/review/", finance_card_transfer_review, name="finance_card_transfer_review"),
    path("finance/card-transfers/attachments/<int:attachment_id>/", finance_card_transfer_attachment_download, name="finance_card_transfer_attachment_download"),
    path("finance/cash/accountable/new/", finance_cash_accountable_issue_create, name="finance_cash_accountable_issue_create"),
    path("finance/cash/accountable-return/new/", finance_accountable_return_create, name="finance_accountable_return_create"),
    path("finance/cash/count/<str:cashbox_type>/", finance_cash_count_create, name="finance_cash_count_create"),
    path("finance/cash/income/new/", finance_cash_income_create, name="finance_cash_income_create"),
    path("finance/cash/transfer/new/", finance_cash_transfer_create, name="finance_cash_transfer_create"),
    path("finance/cash/<int:operation_id>/", finance_cash_operation_detail, name="finance_cash_operation_detail"),
    path("finance/cash/<int:operation_id>/delete/", finance_cash_operation_delete, name="finance_cash_operation_delete"),
    path("finance/cash/<int:operation_id>/edit/", finance_cash_operation_edit, name="finance_cash_operation_edit"),
    path("finance/cash/<int:operation_id>/review/", finance_cash_operation_review, name="finance_cash_operation_review"),
    path("finance/accountable/new/", finance_transaction_create, name="finance_transaction_create"),
    path("finance/accountable/employees/<int:employee_id>/", finance_employee_detail, name="finance_employee_detail"),
    path("finance/accountable/<int:transaction_id>/confirm/", finance_transaction_confirm, name="finance_transaction_confirm"),
    path("finance/income/new/", finance_income_create, name="finance_income_create"),
    path("finance/income/<int:transaction_id>/edit/", finance_income_edit, name="finance_income_edit"),
    path("finance/income/<int:transaction_id>/delete/", finance_income_delete, name="finance_income_delete"),
    path("finance/accountable/<int:transaction_id>/review/", finance_transaction_review, name="finance_transaction_review"),
    path("finance/accountable/<int:transaction_id>/void/", finance_transaction_void, name="finance_transaction_void"),
    path("finance/expenses/new/", finance_expense_create, name="finance_expense_create"),
    path("finance/expenses/<uuid:expense_uuid>/", finance_expense_detail, name="finance_expense_detail"),
    path("finance/expenses/<uuid:expense_uuid>/edit/", finance_expense_edit, name="finance_expense_edit"),
    path("finance/expenses/<uuid:expense_uuid>/delete/", finance_expense_delete, name="finance_expense_delete"),
    path("finance/expenses/<uuid:expense_uuid>/review/", finance_expense_review, name="finance_expense_review"),
    path("finance/expenses/bulk-review/", finance_expense_bulk_review, name="finance_expense_bulk_review"),
    path("finance/expenses/bulk-1c/", finance_expense_bulk_onec, name="finance_expense_bulk_onec"),
    path("finance/receipts/<int:receipt_id>/", finance_receipt_download, name="finance_receipt_download"),
    path("finance/reports/", finance_report, name="finance_report"),
    path("finance/reports/export/", finance_report_export, name="finance_report_export"),
    path("finance/period/close/", finance_period_close, name="finance_period_close"),
    path("finance/period/reopen/", finance_period_reopen, name="finance_period_reopen"),
    path("finance/1c/", finance_onec_gross_profit_dashboard, name="finance_onec_gross_profit_dashboard"),
    path("finance/1c-imports/", finance_onec_import_list, name="finance_onec_import_list"),
    path("finance/1c-imports/cost-control/", finance_onec_cost_control, name="finance_onec_cost_control"),
    path("finance/1c-imports/monthly-profit/upload/", finance_onec_monthly_profit_upload, name="finance_onec_monthly_profit_upload"),
    path("finance/1c-imports/<uuid:batch_id>/preview/", finance_onec_import_preview, name="finance_onec_import_preview"),
    path("finance/1c-imports/<uuid:batch_id>/confirm/", finance_onec_import_confirm, name="finance_onec_import_confirm"),
    path("finance/1c-imports/<uuid:batch_id>/cancel/", finance_onec_import_cancel, name="finance_onec_import_cancel"),
    path("finance/1c-imports/<uuid:batch_id>/", finance_onec_import_detail, name="finance_onec_import_detail"),
    path("development/tasks/", development_task_list, name="development_task_list"),
    path("development/tasks/new/", development_task_create, name="development_task_create"),
    path("development/tasks/<int:task_id>/", development_task_detail, name="development_task_detail"),
    path("development/tasks/<int:task_id>/start/", development_task_start, name="development_task_start"),
    path("development/tasks/<int:task_id>/analysis/start/", development_task_analysis_launch, name="development_task_analysis_launch"),
    path("development/tasks/<int:task_id>/analysis/check/", development_task_analysis_check, name="development_task_analysis_check"),
    path("development/tasks/<int:task_id>/codex/start/", development_task_codex_start, name="development_task_codex_start"),
    path("development/tasks/<int:task_id>/codex/check/", development_task_codex_check, name="development_task_codex_check"),
    path("development/tasks/<int:task_id>/reviews/<int:review_id>/resolve/", development_task_review_resolve, name="development_task_review_resolve"),
    path("development/tasks/<int:task_id>/reviews/<int:review_id>/retry-unknown/", development_task_review_retry_unknown, name="development_task_review_retry_unknown"),
    path("development/tasks/<int:task_id>/reviews/<int:review_id>/resolve-unknown/", development_task_review_resolve_unknown, name="development_task_review_resolve_unknown"),
    path("development/tasks/<int:task_id>/finalize-audit/", development_task_finalize_audit, name="development_task_finalize_audit"),
    path("development/tasks/<int:task_id>/update/", development_task_update, name="development_task_update"),
    path("development/tasks/<int:task_id>/iterations/new/", development_iteration_create, name="development_iteration_create"),
    path("clients/create/", client_create, name="client_create"),
    path("clients/<int:client_id>/edit/", client_edit, name="client_edit"),
    path("clients/<int:client_id>/delete/", client_delete, name="client_delete"),
]
