from django.urls import path
from .views import (
    home,
    pool_list,
    pool_detail,
    water_reading_create,
    water_reading_edit,
    readings_all,
    profile_view,
    users_view,
    billing_info,
    billing_request,
    billing_admin,
    clients_list,
    register,
    pool_create,
    pool_edit,
    client_create,
    client_edit,
    client_delete,
    yandex_suggest,
    confirm_email,
    resend_email_confirmation,
    confirm_phone,
    password_change_inline,
    signup_personal,
    signup_company,
    notifications_list,
    notification_mark_read,
    notifications_mark_all,
    notification_resolve,
    organization_norms,
    invite_create,
    invite_resend,
    invite_accept,
    invite_delete,
    client_staff,
    client_invite_create,
    client_invite_resend,
    client_invite_accept,
    client_invite_delete,
    client_staff_toggle_block,
    client_staff_delete,
    client_staff_change_role,
    staff_toggle_block,
    staff_delete,
    staff_change_role,
    smsru_callback,
    push_subscribe,
    push_unsubscribe,
)
from . import views

urlpatterns = [
    path('', home, name='home'),
    path('index/', views.index, name='index'),
    path('pools/', pool_list, name='pool_list'),
    path('pools/<uuid:pool_uuid>/', pool_detail, name='pool_detail'),
    path('pools/create/', pool_create, name='pool_create'),
    path("pools/<uuid:pool_uuid>/edit/", pool_edit, name="pool_edit"),
    path("api/yandex/suggest/", yandex_suggest, name="yandex_suggest"),
    path('pools/<uuid:pool_uuid>/new-reading/', water_reading_create, name='water_reading_create'),
    path("readings/<uuid:reading_uuid>/edit/", water_reading_edit, name="water_reading_edit"),
    path("readings/all", readings_all, name="readings_all"),
    path("profile/", profile_view, name="profile"),
    path("users/", users_view, name="users"),
    path("notifications/", notifications_list, name="notifications"),
    path("notifications/<int:notification_id>/read/", notification_mark_read, name="notifications_mark_read"),
    path("notifications/read-all/", notifications_mark_all, name="notifications_mark_all"),
    path("notifications/<int:notification_id>/resolve/", notification_resolve, name="notification_resolve"),
    path("organization/norms/", organization_norms, name="organization_norms"),
    path("users/<int:access_id>/block/", staff_toggle_block, name="staff_toggle_block"),
    path("users/<int:access_id>/delete/", staff_delete, name="staff_delete"),
    path("users/<int:access_id>/role/", staff_change_role, name="staff_change_role"),
    path("users/invite/", invite_create, name="invite_create"),
    path("users/invite/<int:invite_id>/resend/", invite_resend, name="invite_resend"),
    path("users/invite/<int:invite_id>/delete/", invite_delete, name="invite_delete"),
    path("invite/<uuid:token>/", invite_accept, name="invite_accept"),
    path("clients/<int:client_id>/staff/", client_staff, name="client_staff"),
    path("clients/<int:client_id>/staff/invite/", client_invite_create, name="client_invite_create"),
    path("clients/<int:client_id>/staff/invite/<int:invite_id>/resend/", client_invite_resend, name="client_invite_resend"),
    path("clients/<int:client_id>/staff/invite/<int:invite_id>/delete/", client_invite_delete, name="client_invite_delete"),
    path("clients/staff/<int:access_id>/block/", client_staff_toggle_block, name="client_staff_toggle_block"),
    path("clients/staff/<int:access_id>/delete/", client_staff_delete, name="client_staff_delete"),
    path("clients/staff/<int:access_id>/role/", client_staff_change_role, name="client_staff_change_role"),
    path("client-invite/<uuid:token>/", client_invite_accept, name="client_invite_accept"),
    path("billing/", billing_info, name="billing"),
    path("billing/request/", billing_request, name="billing_request"),
    path("billing/admin/", billing_admin, name="billing_admin"),
    path("clients/", clients_list, name="clients_list"),
    path("register/", register, name="register"),
    path("signup/personal/", signup_personal, name="signup_personal"),
    path("signup/company/", signup_company, name="signup_company"),
    path("accounts/confirm-email/<uidb64>/<token>/", confirm_email, name="confirm_email"),
    path("accounts/confirm-email/resend/", resend_email_confirmation, name="resend_email_confirmation"),
    path("accounts/confirm-phone/<uuid:token>/", confirm_phone, name="confirm_phone"),
    path("accounts/password-change/", password_change_inline, name="password_change_inline"),
    path("api/smsru/callback/", smsru_callback, name="smsru_callback"),
    path("api/push/subscribe/", push_subscribe, name="push_subscribe"),
    path("api/push/unsubscribe/", push_unsubscribe, name="push_unsubscribe"),
    path("clients/create/", client_create, name="client_create"),
    path("clients/<int:client_id>/edit/", client_edit, name="client_edit"),
    path("clients/<int:client_id>/delete/", client_delete, name="client_delete"),
]
