"""
Django settings for service_site project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import math
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

def _env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")


def _env_float(name, default, *, minimum, maximum):
    raw_value = os.getenv(name, str(default))
    try:
        value = float(raw_value)
    except (TypeError, ValueError) as exc:
        raise ImproperlyConfigured(f"{name} must be a number") from exc
    if not math.isfinite(value) or not minimum <= value <= maximum:
        raise ImproperlyConfigured(
            f"{name} must be between {minimum} and {maximum} seconds"
        )
    return value


def _env_int(name, default, *, minimum, maximum):
    raw_value = os.getenv(name, str(default))
    try:
        value = int(raw_value)
    except (TypeError, ValueError) as exc:
        raise ImproperlyConfigured(f"{name} must be an integer") from exc
    if not minimum <= value <= maximum:
        raise ImproperlyConfigured(f"{name} must be between {minimum} and {maximum}")
    return value

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-local-development-only"
    else:
        raise ImproperlyConfigured("SECRET_KEY must be set when DEBUG=False")

SERVE_MEDIA = _env_bool("SERVE_MEDIA", False)

SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000" if not DEBUG else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", not DEBUG)
SECURE_HSTS_PRELOAD = _env_bool("SECURE_HSTS_PRELOAD", not DEBUG)

allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()]
YANDEX_SUGGEST_API_KEY = os.getenv("YANDEX_SUGGEST_API_KEY", "")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_DEVELOPMENT_MODEL = os.getenv("OPENAI_DEVELOPMENT_MODEL", "gpt-5.6")
DEVELOPMENT_MAX_CORRECTIVE_ITERATIONS = max(
    0, min(int(os.getenv("DEVELOPMENT_MAX_CORRECTIVE_ITERATIONS", "3")), 10)
)
OPENAI_DEVELOPMENT_TIMEOUT_SECONDS = _env_float(
    "OPENAI_DEVELOPMENT_TIMEOUT_SECONDS",
    25,
    minimum=1,
    maximum=60,
)
OPENAI_DEVELOPMENT_MAX_OUTPUT_TOKENS = int(
    os.getenv("OPENAI_DEVELOPMENT_MAX_OUTPUT_TOKENS", "6000")
)
GITHUB_DEVELOPMENT_TOKEN = os.getenv("GITHUB_DEVELOPMENT_TOKEN", "")
GITHUB_DEVELOPMENT_REPOSITORY = os.getenv(
    "GITHUB_DEVELOPMENT_REPOSITORY", "borovikov88/service2"
)
GITHUB_DEVELOPMENT_WORKFLOW = os.getenv(
    "GITHUB_DEVELOPMENT_WORKFLOW", "development-codex.yml"
)
GITHUB_DEVELOPMENT_TIMEOUT_SECONDS = _env_float(
    "GITHUB_DEVELOPMENT_TIMEOUT_SECONDS",
    20,
    minimum=1,
    maximum=60,
)
GITHUB_DEVELOPMENT_PROMPT_MAX_BYTES = _env_int(
    "GITHUB_DEVELOPMENT_PROMPT_MAX_BYTES",
    40000,
    minimum=1000,
    maximum=50000,
)
ONEC_ODATA_BASE_URL = os.getenv("ONEC_ODATA_BASE_URL", "")
ONEC_ODATA_USERNAME = os.getenv("ONEC_ODATA_USERNAME", "")
ONEC_ODATA_PASSWORD = os.getenv("ONEC_ODATA_PASSWORD", "")
ONEC_ODATA_ORGANIZATION_GUIDS = tuple(
    value.strip()
    for value in os.getenv("ONEC_ODATA_ORGANIZATION_GUIDS", "").split(",")
    if value.strip()
)
ONEC_ODATA_TARGET_ORGANIZATION_ID = os.getenv("ONEC_ODATA_TARGET_ORGANIZATION_ID", "")
ONEC_ODATA_TIMEOUT_SECONDS = os.getenv("ONEC_ODATA_TIMEOUT_SECONDS", "15")
ONEC_ODATA_MAX_PAGES = os.getenv("ONEC_ODATA_MAX_PAGES", "100")
ONEC_ODATA_MAX_ROWS = os.getenv("ONEC_ODATA_MAX_ROWS", "100000")
SITE_URL = os.getenv("SITE_URL", "")
SMS_RU_API_ID = os.getenv("SMS_RU_API_ID", "")
SMS_RU_TIMEOUT = int(os.getenv("SMS_RU_TIMEOUT", "8"))
VAPID_PUBLIC_KEY = os.getenv("VAPID_PUBLIC_KEY", "")
VAPID_PRIVATE_KEY = os.getenv("VAPID_PRIVATE_KEY", "")
PHONE_VERIFY_TTL_MINUTES = int(os.getenv("PHONE_VERIFY_TTL_MINUTES", "5"))
PHONE_VERIFY_MAX_ATTEMPTS = int(os.getenv("PHONE_VERIFY_MAX_ATTEMPTS", "3"))
NOTIFICATIONS_PER_PAGE = int(os.getenv("NOTIFICATIONS_PER_PAGE", "20"))
WATER_READING_LIMITS = {
    "ph": {"min": 7.2, "max": 7.8},
    "cl_free": {"min": 0.3, "max": 1.0},
    "cl_total": {"min": 0.3, "max": 1.5},
}


# Application definition

LOGIN_URL = '/accounts/login/'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'pool_service',
    'import_export',
    'django_ckeditor_5'
]

LOGIN_REDIRECT_URL = '/pools/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'pool_service.middleware.RobotsTagMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'pool_service.middleware.TimezoneMiddleware',
    'pool_service.middleware.AuthRedirectMiddleware',
    'pool_service.middleware.SessionSecurityMiddleware',
    'pool_service.middleware.FinanceOnlyRoleMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'service_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
		'django.template.context_processors.media',
                'pool_service.context_processors.brand_context',
                'pool_service.context_processors.plan_status_context',
                'pool_service.context_processors.notifications_context',
                'pool_service.context_processors.push_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'service_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.mysql')

DATABASES = {
    'default': {
        'ENGINE': DB_ENGINE,
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

if DB_ENGINE == 'django.db.backends.mysql':
    DATABASES['default']['OPTIONS'] = {
        'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
    }




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "public_static")
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
PRIVATE_MEDIA_ROOT = os.path.join(BASE_DIR, "private_media")

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", False)
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@rovikpool.ru")
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)
EMAIL_SUBJECT_PREFIX = os.getenv("EMAIL_SUBJECT_PREFIX", "[RovikPool] ")
VAPID_EMAIL = os.getenv("VAPID_EMAIL", DEFAULT_FROM_EMAIL)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "django.core.mail": {"handlers": ["console"], "level": "DEBUG"},
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote'],
    },
}
