# Generated by Django 5.1.6 on 2025-03-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0003_waterreading_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterreading',
            name='cltotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий', null=True),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='performed_works',
            field=models.TextField(blank=True, help_text='Произведённые работы', null=True),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='redox',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='required_materials',
            field=models.TextField(blank=True, help_text='Необходимые материалы', null=True),
        ),
        migrations.AlterField(
            model_name='waterreading',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
