# Generated by Django 5.1.6 on 2025-03-04 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0004_waterreading_cltotal_waterreading_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='pool',
            name='client',
        ),
        migrations.AddField(
            model_name='pool',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='pools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waterreading',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterreading',
            name='performed_works',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterreading',
            name='required_materials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pool_service.organization'),
        ),
        migrations.CreateModel(
            name='PoolAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client_read', 'Клиент (чтение)'), ('client_edit', 'Клиент (редактирование)'), ('manager', 'Менеджер'), ('service', 'Сервисник')], max_length=20)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool_service.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
