# Generated by Django 5.1.6 on 2025-03-04 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0005_organization_remove_pool_client_pool_clients_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='description',
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='pool_service.organization'),
        ),
        migrations.AlterField(
            model_name='poolaccess',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='pool_service.pool'),
        ),
        migrations.AlterField(
            model_name='poolaccess',
            name='role',
            field=models.CharField(choices=[('viewer', 'Просмотр'), ('editor', 'Редактирование'), ('admin', 'Администратор')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Менеджер (просмотр всех бассейнов)'), ('service', 'Сервисник (внесение данных)'), ('admin', 'Администратор (управление бассейнами и пользователями)')], max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='pool_service.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
