# Generated by Django 5.1.6 on 2025-03-04 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0006_remove_pool_clients_remove_pool_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='pool_service.organization'),
        ),
    ]
