# Generated by Django 5.1.6 on 2025-03-05 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0007_alter_pool_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterreading',
            name='chlorine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterreading',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterreading',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterreading', to='pool_service.pool'),
        ),
        migrations.AlterField(
            model_name='waterreading',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
