# Generated by Django 5.1.6 on 2025-03-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0008_alter_waterreading_chlorine_alter_waterreading_ph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolaccess',
            name='role',
            field=models.CharField(choices=[('viewer', 'Просмотр'), ('editor', 'Редактирование')], max_length=20),
        ),
    ]
