# Generated by Django 5.1.6 on 2025-03-05 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0009_alter_poolaccess_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pool_service.client'),
            preserve_default=False,
        ),
    ]
