# Generated by Django 5.1.6 on 2025-03-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0010_pool_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание бассейна'),
        ),
    ]
