# Generated by Django 5.1.6 on 2025-03-06 04:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0011_pool_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание бассейна'),
        ),
    ]
