# Generated by Django 5.1.6 on 2025-03-07 06:01

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0012_alter_pool_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='pool',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание бассейна'),
        ),
    ]
