# Generated by Django 5.1.6 on 2025-03-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0013_client_last_name_pool_name_alter_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
