# Generated by Django 5.1.6 on 2025-03-07 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0014_remove_client_last_name_alter_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='name',
        ),
        migrations.AlterField(
            model_name='organizationaccess',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='pool_service.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='organizationaccess',
            name='role',
            field=models.CharField(choices=[('manager', 'Менеджер (просмотр всех бассейнов)'), ('service', 'Сервисник (внесение данных)'), ('admin', 'Администратор (управление бассейнами и пользователями)')], max_length=20, verbose_name='Роль'),
        ),
    ]
