# Generated by Django 5.1.6 on 2025-11-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0016_alter_organizationaccess_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterreading',
            old_name='chlorine',
            new_name='cl_free',
        ),
    ]
