# Generated by Django 5.1.6 on 2025-11-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0017_rename_chlorine_waterreading_cl_free'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterreading',
            old_name='cltotal',
            new_name='cl_total',
        ),
        migrations.RenameField(
            model_name='waterreading',
            old_name='redox',
            new_name='redox_dosing_station',
        ),
    ]
