# Generated by Django 5.1.6 on 2025-11-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0018_rename_cltotal_waterreading_cl_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterreading',
            name='cl_free_dosing_station',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='cl_total_dosing_station',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='ph_dosing_station',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
