# Generated by Django 4.2.26 on 2025-12-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0022_client_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('private', 'Частный клиент'), ('legal', 'Юридическое лицо')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='inn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя/название'),
        ),
        migrations.AlterField(
            model_name='organizationaccess',
            name='role',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('service', 'Сервисник'), ('admin', 'Администратор')], max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='poolaccess',
            name='role',
            field=models.CharField(choices=[('viewer', 'Просмотр'), ('editor', 'Редактор')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='Europe/Moscow', help_text='Часовой пояс пользователя, например, Europe/Moscow', max_length=50),
        ),
    ]
