# Generated by Django 5.1.6 on 2025-12-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0023_client_client_type_client_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='depth_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='depth_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='diameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='dosing_station',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pool',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='overflow_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='pool_type',
            field=models.CharField(choices=[('overflow', 'Переливной'), ('skimmer', 'Скиммерный')], default='skimmer', max_length=20),
        ),
        migrations.AddField(
            model_name='pool',
            name='shape',
            field=models.CharField(choices=[('rect', 'Прямоугольный'), ('round', 'Круглый'), ('oval', 'Овальный'), ('free', 'Произвольная форма')], default='rect', max_length=20),
        ),
        migrations.AddField(
            model_name='pool',
            name='surface_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='variable_depth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pool',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
