# Generated by Django 5.1.6 on 2026-01-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0027_organization_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationaccess',
            name='role',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('service', 'Сервис'), ('admin', 'Администратор')], max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='role',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('service', 'Сервис'), ('admin', 'Администратор')], default='service', max_length=20),
        ),
    ]
