# Generated by Codex on 2026-01-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0030_profile_email_confirmed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="contact_position",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
