# Generated by Django 5.1.6 on 2026-01-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0041_organization_invite_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationaccess',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('manager', 'Менеджер'), ('service', 'Сервис'), ('admin', 'Администратор')], max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('manager', 'Менеджер'), ('service', 'Сервис'), ('admin', 'Администратор')], default='service', max_length=20),
        ),
        migrations.AlterField(
            model_name='pool',
            name='service_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Раз в неделю'), ('twice_monthly', 'Два раза в месяц'), ('monthly', 'Раз в месяц'), ('bimonthly', 'Раз в 2 месяца'), ('quarterly', 'Раз в квартал'), ('twice_yearly', 'Два раза в год'), ('yearly', 'Раз в год')], max_length=20, null=True),
        ),
    ]
