# Generated by Django 5.1.6 on 2026-01-23 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0042_alter_organizationaccess_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('service', 'service'), ('project', 'project'), ('sales', 'sales'), ('tender', 'tender')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('srv_new', 'service_new'), ('srv_in_progress', 'service_in_progress'), ('srv_done', 'service_done'), ('srv_blocked', 'service_blocked'), ('prj_idea', 'project_idea'), ('prj_design', 'project_design'), ('prj_build', 'project_build'), ('prj_commission', 'project_commission'), ('prj_done', 'project_done'), ('prj_hold', 'project_hold'), ('sale_lead', 'sales_lead'), ('sale_qualify', 'sales_qualify'), ('sale_offer', 'sales_offer'), ('sale_contract', 'sales_contract'), ('sale_won', 'sales_won'), ('sale_lost', 'sales_lost'), ('tend_prepare', 'tender_prepare'), ('tend_submitted', 'tender_submitted'), ('tend_shortlist', 'tender_shortlist'), ('tend_won', 'tender_won'), ('tend_lost', 'tender_lost'), ('tend_cancel', 'tender_cancel')], default='srv_new', max_length=40)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('service_works', models.TextField(blank=True)),
                ('equipment_replacement', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_items', to='pool_service.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_created_items', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_items', to='pool_service.organization')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_items', to='pool_service.pool')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_responsible_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'direction'], name='crm_org_dir_idx')],
            },
        ),
    ]
