# Generated by Django 5.1.6 on 2026-02-08

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0049_pool_object_type_and_water_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pool",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                null=True,
                verbose_name="Описание объекта",
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="service_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekly", "Раз в неделю"),
                    ("twice_monthly", "Раз в 2 недели"),
                    ("monthly", "Раз в месяц"),
                    ("bimonthly", "Раз в 2 месяца"),
                    ("quarterly", "Раз в квартал"),
                    ("twice_yearly", "Два раза в год"),
                    ("yearly", "Раз в год"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
