# Generated by Django 5.1.6 on 2026-02-10 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0050_alter_pool_description_alter_pool_service_frequency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Общая'), ('private', 'Личная')], default='public', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий')], default='normal', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_service_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_tasks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tasks', to='pool_service.organization')),
                ('responsibles', models.ManyToManyField(related_name='service_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTaskChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создание'), ('updated', 'Изменение'), ('completed', 'Выполнено'), ('reopened', 'Возобновлено'), ('moved', 'Перенос')], max_length=16)),
                ('field_name', models.CharField(blank=True, max_length=80)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='pool_service.servicetask')),
            ],
        ),
        migrations.AddIndex(
            model_name='servicetask',
            index=models.Index(fields=['organization', 'start_date'], name='task_org_start_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetask',
            index=models.Index(fields=['organization', 'end_date'], name='task_org_end_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetaskchange',
            index=models.Index(fields=['task', 'created_at'], name='task_change_idx'),
        ),
    ]
