# Generated by Django 5.1.6 on 2026-02-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0051_servicetask_servicetaskchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetask',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
