# Generated by Django 5.1.6 on 2026-03-30 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0057_pushsubscription_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetask',
            name='auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_tasks_by_client', to='pool_service.client'),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='crm_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tasks', to='pool_service.crmitem'),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tasks', to='pool_service.servicetask'),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='payload_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_tasks_by_pool', to='pool_service.pool'),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='primary_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_service_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='source_type',
            field=models.CharField(choices=[('system', 'Система'), ('service_staff', 'Сотрудник сервисной компании'), ('pool_staff', 'Сотрудник бассейна'), ('manager', 'Менеджер')], default='service_staff', max_length=32),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('waiting', 'Ожидание'), ('done', 'Выполнена'), ('cancelled', 'Отменена')], default='new', max_length=24),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='task_type',
            field=models.CharField(choices=[('scheduled_visit', 'Плановый выезд'), ('manual', 'Ручная задача'), ('supply_request', 'Поставка материалов'), ('crm_followup', 'CRM-сопровождение'), ('issue_resolution', 'Решение проблемы')], default='manual', max_length=32),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='water_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tasks', to='pool_service.waterreading'),
        ),
        migrations.AddIndex(
            model_name='servicetask',
            index=models.Index(fields=['organization', 'task_type'], name='task_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetask',
            index=models.Index(fields=['organization', 'status'], name='task_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetask',
            index=models.Index(fields=['pool', 'status'], name='task_pool_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetask',
            index=models.Index(fields=['water_reading', 'task_type'], name='task_reading_type_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetask',
            index=models.Index(fields=['primary_responsible', 'status'], name='task_primary_status_idx'),
        ),
    ]
