# Generated by Django 5.1.6 on 2026-07-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0060_crmitem_archive_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crmitem",
            name="stage",
            field=models.CharField(
                choices=[
                    ("srv_new", "service_new"),
                    ("srv_in_progress", "service_in_progress"),
                    ("srv_blocked", "service_waiting_supplier"),
                    ("srv_wait_stock", "service_waiting_stock"),
                    ("srv_sent_pool", "service_sent_to_pool"),
                    ("srv_done", "service_done"),
                    ("prj_idea", "project_idea"),
                    ("prj_design", "project_design"),
                    ("prj_build", "project_build"),
                    ("prj_commission", "project_commission"),
                    ("prj_done", "project_done"),
                    ("prj_hold", "project_hold"),
                    ("sale_lead", "sales_lead"),
                    ("sale_qualify", "sales_qualify"),
                    ("sale_offer", "sales_offer"),
                    ("sale_contract", "sales_contract"),
                    ("sale_won", "sales_won"),
                    ("sale_lost", "sales_lost"),
                    ("tend_prepare", "tender_prepare"),
                    ("tend_submitted", "tender_submitted"),
                    ("tend_shortlist", "tender_shortlist"),
                    ("tend_won", "tender_won"),
                    ("tend_lost", "tender_lost"),
                    ("tend_cancel", "tender_cancel"),
                ],
                default="srv_new",
                max_length=40,
            ),
        ),
    ]
