# Generated by Django 5.1.6 on 2026-07-26 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0064_accountant_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accountabletransaction",
            name="review_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="accountabletransaction",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accountabletransaction",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_accountable_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountabletransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "На проверке"),
                    ("approved", "Подтверждён"),
                    ("rejected", "Отклонён"),
                ],
                default="approved",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="receipt_missing_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="accountabletransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("issue", "Выдача"),
                    ("return", "Возврат"),
                    ("adjustment_in", "Увеличение остатка"),
                    ("adjustment_out", "Уменьшение остатка"),
                    ("client_payment", "Приход от клиента"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddIndex(
            model_name="accountabletransaction",
            index=models.Index(fields=["organization", "status"], name="acct_org_status_idx"),
        ),
    ]
