# Generated by Django 5.1.6 on 2026-07-26 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0065_accountabletransaction_review_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountableTransactionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создан'), ('edit_requested', 'Запрошено изменение'), ('delete_requested', 'Запрошено удаление'), ('updated', 'Изменён'), ('deleted', 'Удалён'), ('rejected', 'Отклонён'), ('voided', 'Аннулирован')], max_length=24)),
                ('note', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='accountabletransaction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountable_transactions', to='pool_service.client'),
        ),
        migrations.AddField(
            model_name='accountabletransaction',
            name='pending_action',
            field=models.CharField(blank=True, choices=[('edit', 'Изменение'), ('delete', 'Удаление')], max_length=16),
        ),
        migrations.AddField(
            model_name='accountabletransaction',
            name='pending_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='accountabletransaction',
            name='pending_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountabletransaction',
            name='pending_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_accountable_transaction_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accountabletransaction',
            index=models.Index(fields=['organization', 'pending_action'], name='acct_org_pending_idx'),
        ),
        migrations.AddField(
            model_name='accountabletransactionchange',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accountable_transaction_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountabletransactionchange',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='pool_service.accountabletransaction'),
        ),
        migrations.AddIndex(
            model_name='accountabletransactionchange',
            index=models.Index(fields=['transaction', 'created_at'], name='acct_change_idx'),
        ),
    ]
