# Generated by Django 5.1.6 on 2026-07-27 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0067_update_expense_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('manager_income', 'Поступление в кассу ККМ'), ('transfer_to_company', 'Сдача выручки в кассу компании')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('occurred_on', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cash_operations', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_cash_operations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_operations', to='pool_service.organization')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_cash_operations', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_cash_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashOperationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создана'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], max_length=24)),
                ('note', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_operation_changes', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='pool_service.cashoperation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='cashoperation',
            index=models.Index(fields=['organization', 'occurred_on'], name='cash_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cashoperation',
            index=models.Index(fields=['organization', 'status'], name='cash_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cashoperation',
            index=models.Index(fields=['manager', 'occurred_on'], name='cash_manager_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cashoperationchange',
            index=models.Index(fields=['operation', 'created_at'], name='cash_change_idx'),
        ),
    ]
