# Generated by Django 5.1.6 on 2026-07-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0068_cashoperation_cashoperationchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashoperation',
            name='accountable_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_operations', to='pool_service.accountabletransaction'),
        ),
        migrations.AlterField(
            model_name='cashoperation',
            name='operation_type',
            field=models.CharField(choices=[('manager_income', 'Поступление в кассу ККМ'), ('transfer_to_company', 'Сдача выручки в кассу компании'), ('accountable_issue', 'Выдача подотчёта из ККМ')], max_length=32),
        ),
    ]
