# Generated by Django 5.1.6 on 2026-07-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0069_cashoperation_accountable_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoperationchange',
            name='action',
            field=models.CharField(choices=[('created', 'Создана'), ('updated', 'Изменена'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], max_length=24),
        ),
    ]
