# Generated by Django 5.1.6 on 2026-07-27 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0070_alter_cashoperationchange_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoperation',
            name='operation_type',
            field=models.CharField(choices=[('manager_income', 'Поступление в кассу ККМ'), ('transfer_to_company', 'Сдача выручки в кассу компании'), ('accountable_issue', 'Выдача подотчёта из ККМ'), ('accountable_return', 'Возврат подотчёта в ККМ')], max_length=32),
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashbox_type', models.CharField(choices=[('company', 'Касса организации'), ('kkm', 'Касса ККМ')], max_length=16)),
                ('occurred_on', models.DateField()),
                ('denominations', models.JSONField(blank=True, default=dict)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_counts', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager_cash_counts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_counts', to='pool_service.organization')),
            ],
            options={
                'ordering': ['-occurred_on', '-id'],
                'indexes': [models.Index(fields=['organization', 'cashbox_type', 'occurred_on'], name='cash_count_box_date_idx'), models.Index(fields=['manager', 'occurred_on'], name='cash_count_manager_idx')],
            },
        ),
    ]
