# Generated by Django 5.1.6 on 2026-07-27 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_kkm_cash_operations(apps, schema_editor):
    CashOperation = apps.get_model("pool_service", "CashOperation")
    CashOperation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0071_alter_cashoperation_operation_type_cashcount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoperation',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager_cash_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashoperation',
            name='operation_type',
            field=models.CharField(choices=[('manager_income', 'Поступление в кассу ККМ'), ('transfer_to_company', 'Сдача выручки в кассу компании'), ('accountable_issue', 'Выдача подотчёта из ККМ'), ('accountable_return', 'Возврат подотчёта в ККМ'), ('cash_count_income', 'Приход по пересчёту ККМ'), ('cash_count_write_off', 'Списание по пересчёту ККМ')], max_length=32),
        ),
        migrations.RunPython(clear_kkm_cash_operations, migrations.RunPython.noop),
    ]
