# Generated by Django 5.1.6 on 2026-07-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0076_webauthn_credential_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='service_details_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='service_monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
