# Generated by Django 5.1.6 on 2026-08-06 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0080_dataauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='delete_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_pools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pool',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='delete_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_water_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
