# Generated by Django 5.1.6 on 2026-08-06 12:07

import django.db.models.deletion
import pool_service.models
import pool_service.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0081_pool_delete_reason_pool_deleted_at_pool_deleted_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OneCImportBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("import_type", models.CharField(choices=[("monthly_profit", "Валовая прибыль по месяцам")], default="monthly_profit", max_length=40, verbose_name="Тип импорта")),
                ("original_filename", models.CharField(max_length=255, verbose_name="Исходное имя файла")),
                ("stored_file", models.FileField(max_length=160, storage=pool_service.storage.PrivateMediaStorage(), upload_to=pool_service.models.onec_import_upload_to, verbose_name="Приватный файл")),
                ("file_sha256", models.CharField(max_length=64, verbose_name="SHA-256")),
                ("file_size", models.PositiveBigIntegerField(default=0, verbose_name="Размер файла")),
                ("status", models.CharField(choices=[("uploaded", "Загружен"), ("previewed", "Предпросмотр"), ("confirmed", "Подтверждён"), ("failed", "Ошибка"), ("cancelled", "Отменён")], default="uploaded", max_length=16, verbose_name="Статус")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="Загружен")),
                ("confirmed_at", models.DateTimeField(blank=True, null=True, verbose_name="Подтверждён")),
                ("rows_detected", models.PositiveIntegerField(default=0, verbose_name="Обнаружено строк")),
                ("rows_imported", models.PositiveIntegerField(default=0, verbose_name="Импортировано строк")),
                ("warnings_count", models.PositiveIntegerField(default=0, verbose_name="Предупреждений")),
                ("error_message", models.TextField(blank=True, verbose_name="Сообщение об ошибке")),
                ("parser_version", models.CharField(default="1", max_length=20, verbose_name="Версия парсера")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Метаданные")),
                ("confirmed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="confirmed_onec_batches", to=settings.AUTH_USER_MODEL, verbose_name="Подтвердил")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="onec_import_batches", to="pool_service.organization", verbose_name="Организация")),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="uploaded_onec_batches", to=settings.AUTH_USER_MODEL, verbose_name="Загрузил")),
            ],
            options={
                "verbose_name": "Загрузка отчёта 1С",
                "verbose_name_plural": "Загрузки отчётов 1С",
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OneCMonthlyProfit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_month", models.DateField(verbose_name="Месяц")),
                ("source_row_number", models.PositiveIntegerField(verbose_name="Номер строки источника")),
                ("nomenclature", models.CharField(max_length=500, verbose_name="Номенклатура")),
                ("article", models.CharField(blank=True, max_length=120, verbose_name="Артикул или код")),
                ("quantity", models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name="Количество")),
                ("revenue", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="Выручка")),
                ("cost", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="Себестоимость")),
                ("gross_profit", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="Валовая прибыль")),
                ("profitability_percent", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name="Рентабельность, %")),
                ("source_data", models.JSONField(blank=True, default=dict, verbose_name="Исходные данные")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("import_batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="monthly_profit_rows", to="pool_service.onecimportbatch", verbose_name="Загрузка")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="onec_monthly_profit_rows", to="pool_service.organization", verbose_name="Организация")),
            ],
            options={
                "verbose_name": "Строка валовой прибыли 1С",
                "verbose_name_plural": "Строки валовой прибыли 1С",
                "ordering": ["period_month", "source_row_number", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="onecimportbatch",
            index=models.Index(fields=["organization", "import_type", "uploaded_at"], name="onec_batch_org_type_at_idx"),
        ),
        migrations.AddConstraint(
            model_name="onecimportbatch",
            constraint=models.UniqueConstraint(fields=("organization", "import_type", "file_sha256"), name="unique_onec_file_per_org_type"),
        ),
        migrations.AddIndex(
            model_name="onecmonthlyprofit",
            index=models.Index(fields=["organization", "period_month"], name="onec_profit_org_month_idx"),
        ),
        migrations.AddIndex(
            model_name="onecmonthlyprofit",
            index=models.Index(fields=["organization", "nomenclature"], name="onec_profit_org_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="onecmonthlyprofit",
            constraint=models.UniqueConstraint(fields=("import_batch", "source_row_number", "period_month"), name="unique_onec_batch_row_month"),
        ),
    ]
