# Generated by Django 5.1.6 on 2026-08-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0082_onecimportbatch_onecmonthlyprofit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onecmonthlyprofit",
            name="nomenclature_type",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Тип номенклатуры",
            ),
        ),
    ]
