# Generated by Django 5.1.6 on 2026-08-09 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0083_onecmonthlyprofit_nomenclature_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OneCReportPeriodState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_type", models.CharField(choices=[("monthly_profit", "Валовая прибыль по месяцам")], default="monthly_profit", max_length=40, verbose_name="Тип отчёта")),
                ("period_month", models.DateField(verbose_name="Месяц")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("active_batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="active_period_states", to="pool_service.onecimportbatch", verbose_name="Активная загрузка")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="onec_report_period_states", to="pool_service.organization", verbose_name="Организация")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_onec_period_states", to=settings.AUTH_USER_MODEL, verbose_name="Обновил")),
            ],
            options={
                "verbose_name": "Активная версия месяца отчёта 1С",
                "verbose_name_plural": "Активные версии месяцев отчётов 1С",
                "ordering": ["organization_id", "report_type", "period_month"],
            },
        ),
        migrations.CreateModel(
            name="OneCReportPeriodActivation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activated_at", models.DateTimeField(auto_now_add=True, verbose_name="Активировано")),
                ("activated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="onec_period_activations", to=settings.AUTH_USER_MODEL, verbose_name="Активировал")),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="period_activations", to="pool_service.onecimportbatch", verbose_name="Активированная загрузка")),
                ("replaced_batch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="replaced_period_activations", to="pool_service.onecimportbatch", verbose_name="Заменённая загрузка")),
                ("period_state", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activation_history", to="pool_service.onecreportperiodstate", verbose_name="Состояние месяца")),
            ],
            options={
                "verbose_name": "Активация версии месяца отчёта 1С",
                "verbose_name_plural": "История активаций месяцев отчётов 1С",
                "ordering": ["period_state_id", "activated_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="onecreportperiodstate",
            constraint=models.UniqueConstraint(fields=("organization", "report_type", "period_month"), name="unique_onec_period_state_org_type_month"),
        ),
    ]
