# Generated by Django 5.1.6 on 2026-08-09 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0085_backfill_onec_report_period_states"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Исходная задача')),
                ('business_goal', models.TextField(blank=True, verbose_name='Бизнес-цель')),
                ('definition_of_done', models.TextField(blank=True, verbose_name='Definition of Done')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Обычный'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=16, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('analysis', 'Анализ'), ('ready_for_codex', 'Готова к передаче Codex'), ('codex_working', 'Codex работает'), ('testing', 'Тестирование'), ('review', 'Проверка'), ('revision', 'Требуется доработка'), ('blocked', 'Заблокирована'), ('done', 'Выполнена'), ('failed', 'Не выполнена'), ('cancelled', 'Отменена')], default='new', max_length=24, verbose_name='Статус')),
                ('current_stage', models.CharField(choices=[('analysis', 'Анализ'), ('development', 'Разработка'), ('testing', 'Тестирование'), ('review', 'Review'), ('completion', 'Завершение')], default='analysis', max_length=20, verbose_name='Текущий этап')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало работы')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('completed_work', models.TextField(blank=True, verbose_name='Что уже сделано')),
                ('current_activity', models.TextField(blank=True, verbose_name='Что происходит сейчас')),
                ('blockers', models.TextField(blank=True, verbose_name='Проблемы / blockers')),
                ('final_summary', models.TextField(blank=True, verbose_name='Итоговое резюме')),
                ('execution_result', models.TextField(blank=True, verbose_name='Результат выполнения')),
                ('automation_metadata', models.JSONField(blank=True, default=dict, verbose_name='Данные автоматизации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_development_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_tasks', to='pool_service.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Задача разработки',
                'verbose_name_plural': 'Задачи разработки',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration_number', models.PositiveIntegerField(verbose_name='Номер итерации')),
                ('executor_type', models.CharField(choices=[('codex', 'Codex'), ('chatgpt', 'ChatGPT'), ('human', 'Человек'), ('system', 'Система'), ('other', 'Другой')], default='codex', max_length=16, verbose_name='Тип исполнителя')),
                ('prompt', models.TextField(blank=True, verbose_name='Prompt для Codex')),
                ('response', models.TextField(blank=True, verbose_name='Ответ Codex')),
                ('result_summary', models.TextField(blank=True, verbose_name='Краткое резюме результата')),
                ('status', models.CharField(choices=[('new', 'Создана'), ('working', 'В работе'), ('testing', 'Тестирование'), ('review', 'На проверке'), ('accepted', 'Принята'), ('revision', 'На доработке'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], default='new', max_length=16, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('changed_files', models.TextField(blank=True, verbose_name='Изменённые файлы')),
                ('test_result', models.TextField(blank=True, verbose_name='Результат тестов')),
                ('tests_passed', models.PositiveIntegerField(default=0, verbose_name='Успешных тестов')),
                ('tests_failed', models.PositiveIntegerField(default=0, verbose_name='Упавших тестов')),
                ('technical_errors', models.TextField(blank=True, verbose_name='Технические ошибки')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='Замечания reviewer')),
                ('next_prompt', models.TextField(blank=True, verbose_name='Следующий prompt')),
                ('automation_metadata', models.JSONField(blank=True, default=dict, verbose_name='Данные автоматизации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='development_iterations', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='pool_service.developmenttask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Итерация разработки',
                'verbose_name_plural': 'Итерации разработки',
                'ordering': ['iteration_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentTaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Задача создана'), ('status_changed', 'Статус изменён'), ('iteration_added', 'Итерация добавлена'), ('test_result', 'Результат тестов'), ('note', 'Заметка')], max_length=24, verbose_name='Тип события')),
                ('message', models.CharField(max_length=500, verbose_name='Событие')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='development_task_events', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pool_service.developmenttask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Событие задачи разработки',
                'verbose_name_plural': 'События задач разработки',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='developmenttask',
            index=models.Index(fields=['organization', 'status'], name='dev_task_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='developmenttask',
            index=models.Index(fields=['organization', 'updated_at'], name='dev_task_org_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='developmentiteration',
            constraint=models.UniqueConstraint(fields=('task', 'iteration_number'), name='dev_iter_task_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='developmenttaskevent',
            index=models.Index(fields=['task', 'created_at'], name='dev_event_task_at_idx'),
        ),
    ]
