# Generated by Django 5.1.6 on 2026-08-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0086_developmenttask_developmentiteration_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="posted_to_1c",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expense",
            name="posted_to_1c_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="posted_to_1c_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="posted_expenses_to_1c", to=settings.AUTH_USER_MODEL),
        ),
    ]
