# Generated by Django 5.1.6 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0087_expense_posted_to_1c"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensechange",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("updated", "Изменён"),
                    ("approved", "Подтверждён"),
                    ("rejected", "Отклонён"),
                    ("posted_1c", "Внесён в 1С"),
                    ("unposted_1c", "Снята отметка 1С"),
                ],
                max_length=16,
            ),
        ),
    ]
