# Generated by Django 5.1.6 on 2026-08-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0091_onecmonthlyprofit_analytical_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="onecmonthlyprofit",
            name="customer_name",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Покупатель"
            ),
        ),
        migrations.AddField(
            model_name="onecmonthlyprofit",
            name="document_name",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Документ"
            ),
        ),
        migrations.AddField(
            model_name="onecmonthlyprofit",
            name="manager_name",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="Менеджер"
            ),
        ),
    ]
