# Generated by Django 5.1.6 on 2026-08-15 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0092_onecmonthlyprofit_customer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('view_cashflow', 'Can view cash flow'), ('import_cashflow', 'Can import cash flow'), ('manage_cashflow_classification', 'Can manage cash flow classification'), ('view_payroll_summary', 'Can view payroll summary'), ('view_payroll_personal', 'Can view personal payroll data'), ('import_payroll', 'Can import payroll'), ('manage_employee_mapping', 'Can manage employee mapping')]},
        ),
        migrations.AddField(
            model_name='onecimportbatch',
            name='period_first',
            field=models.DateField(blank=True, null=True, verbose_name='Первый месяц'),
        ),
        migrations.AddField(
            model_name='onecimportbatch',
            name='period_last',
            field=models.DateField(blank=True, null=True, verbose_name='Последний месяц'),
        ),
        migrations.AlterField(
            model_name='onecimportbatch',
            name='import_type',
            field=models.CharField(choices=[('monthly_profit', 'Валовая прибыль по месяцам'), ('payroll', 'Расчёты с персоналом'), ('cashflow', 'Движения по статьям и месяцам')], default='monthly_profit', max_length=40, verbose_name='Тип импорта'),
        ),
        migrations.AlterField(
            model_name='onecreportperiodstate',
            name='report_type',
            field=models.CharField(choices=[('monthly_profit', 'Валовая прибыль по месяцам'), ('payroll', 'Расчёты с персоналом'), ('cashflow', 'Движения по статьям и месяцам')], default='monthly_profit', max_length=40, verbose_name='Тип отчёта'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('display_name', models.CharField(max_length=500)),
                ('department_name', models.CharField(blank=True, max_length=300)),
                ('position_name', models.CharField(blank=True, max_length=300)),
                ('employment_status', models.CharField(choices=[('employed', 'Работает'), ('on_leave', 'Временно отсутствует'), ('dismissed', 'Уволен')], default='employed', max_length=16)),
                ('hired_at', models.DateField(blank=True, null=True)),
                ('dismissed_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='pool_service.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOneCIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=500)),
                ('normalized_name', models.CharField(db_index=True, max_length=500)),
                ('normalized_department_name', models.CharField(blank=True, max_length=300)),
                ('source_identity_key', models.CharField(blank=True, max_length=64)),
                ('onec_employee_id', models.CharField(blank=True, max_length=120, null=True)),
                ('personnel_number', models.CharField(blank=True, max_length=120, null=True)),
                ('department_name', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('auto_matched', 'Сопоставлен автоматически'), ('manually_matched', 'Сопоставлен вручную'), ('needs_confirmation', 'Требует подтверждения'), ('not_found', 'Не найден'), ('ambiguous', 'Неоднозначное совпадение'), ('excluded', 'Исключён')], max_length=24)),
                ('match_method', models.CharField(choices=[('exact_normalized', 'Точное нормализованное ФИО'), ('external_id', 'Идентификатор 1С'), ('personnel_number', 'Табельный номер'), ('manual', 'Вручную'), ('none', 'Нет сопоставления')], default='none', max_length=24)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_employee_onec_identities', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onec_identities', to='pool_service.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_onec_identities', to='pool_service.organization')),
            ],
            options={
                'ordering': ['normalized_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField()),
                ('source_row_number', models.PositiveIntegerField()),
                ('department_name', models.CharField(blank=True, max_length=300)),
                ('employee_raw_name', models.CharField(max_length=500)),
                ('employee_normalized_name', models.CharField(db_index=True, max_length=500)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('accrued', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('source_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_rows', to='pool_service.employeeonecidentity')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_rows', to='pool_service.onecimportbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_rows', to='pool_service.organization')),
            ],
            options={
                'ordering': ['period_month', 'source_row_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CashFlowArticleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=500)),
                ('normalized_article_name', models.CharField(max_length=500)),
                ('management_category', models.CharField(blank=True, max_length=300)),
                ('flow_type', models.CharField(choices=[('operating', 'Операционный'), ('investing', 'Инвестиционный'), ('financing', 'Финансовый'), ('internal', 'Внутренний'), ('unclassified', 'Не классифицирован')], default='unclassified', max_length=20)),
                ('pnl_treatment', models.CharField(choices=[('exclude', 'Исключить'), ('direct_expense', 'Прямой расход'), ('direct_income', 'Прямой доход'), ('reconciliation_only', 'Только сверка'), ('requires_accrual_source', 'Требует источника начислений'), ('needs_review', 'Требует проверки')], default='needs_review', max_length=32)),
                ('classification_status', models.CharField(choices=[('confirmed', 'Подтверждена'), ('needs_review', 'Требует проверки'), ('unclassified', 'Не классифицирована')], default='unclassified', max_length=20)),
                ('is_internal_turnover', models.BooleanField(default=False)),
                ('include_in_external_cashflow', models.BooleanField(default=True)),
                ('is_dividend', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_article_mappings', to='pool_service.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cashflow_article_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['article_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'normalized_article_name'), name='unique_cashflow_article_per_org')],
            },
        ),
        migrations.CreateModel(
            name='CashFlowRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField()),
                ('source_row_number', models.PositiveIntegerField()),
                ('source_reference', models.CharField(blank=True, max_length=300)),
                ('article_raw', models.CharField(max_length=500)),
                ('normalized_article_name', models.CharField(db_index=True, max_length=500)),
                ('document_raw', models.CharField(max_length=700)),
                ('receipts', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payments', models.DecimalField(decimal_places=2, max_digits=20)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, max_digits=20)),
                ('source_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashflow_rows', to='pool_service.onecimportbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_rows', to='pool_service.organization')),
            ],
            options={
                'ordering': ['period_month', 'source_row_number', 'id'],
                'indexes': [models.Index(fields=['organization', 'period_month'], name='cashflow_org_month_idx'), models.Index(fields=['organization', 'normalized_article_name'], name='cashflow_org_article_idx')],
                'constraints': [models.UniqueConstraint(fields=('import_batch', 'source_row_number', 'period_month'), name='unique_cashflow_batch_row_month')],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'is_active'], name='employee_org_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('organization', 'user'), name='unique_employee_user_per_org'),
        ),
        migrations.AddIndex(
            model_name='employeeonecidentity',
            index=models.Index(fields=['organization', 'normalized_name'], name='onec_emp_org_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeonecidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('onec_employee_id__isnull', False), models.Q(('onec_employee_id', ''), _negated=True)), fields=('organization', 'onec_employee_id'), name='unique_onec_employee_id_per_org'),
        ),
        migrations.AddConstraint(
            model_name='employeeonecidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('personnel_number__isnull', False), models.Q(('personnel_number', ''), _negated=True)), fields=('organization', 'personnel_number'), name='unique_personnel_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='employeeonecidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('source_identity_key', ''), _negated=True), fields=('organization', 'source_identity_key'), name='unique_source_employee_per_org'),
        ),
        migrations.AddIndex(
            model_name='payrollrow',
            index=models.Index(fields=['organization', 'period_month'], name='payroll_org_month_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrow',
            constraint=models.UniqueConstraint(fields=('import_batch', 'source_row_number', 'period_month'), name='unique_payroll_batch_row_month'),
        ),
    ]
