# Generated by Django 5.1.6 on 2026-09-09 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0099_onec_auto_refresh_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onecimportbatch',
            name='import_type',
            field=models.CharField(choices=[('monthly_profit', 'Валовая прибыль по месяцам'), ('payroll', 'Расчёты с персоналом'), ('payroll_accrual', 'Начисления ФОТ из 1С'), ('cashflow', 'Движения по статьям и месяцам')], default='monthly_profit', max_length=40, verbose_name='Тип импорта'),
        ),
        migrations.AlterField(
            model_name='onecreportperiodstate',
            name='report_type',
            field=models.CharField(choices=[('monthly_profit', 'Валовая прибыль по месяцам'), ('payroll', 'Расчёты с персоналом'), ('payroll_accrual', 'Начисления ФОТ из 1С'), ('cashflow', 'Движения по статьям и месяцам')], default='monthly_profit', max_length=40, verbose_name='Тип отчёта'),
        ),
        migrations.CreateModel(
            name='PayrollAccrualMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField()),
                ('accrued', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency_guid', models.UUIDField()),
                ('source_organization_guids', models.JSONField(default=list)),
                ('source_rows', models.PositiveIntegerField()),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_accrual_months', to='pool_service.onecimportbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_accrual_months', to='pool_service.organization')),
            ],
            options={
                'ordering': ['period_month', 'id'],
                'constraints': [models.UniqueConstraint(fields=('import_batch', 'period_month'), name='unique_payroll_accrual_month')],
            },
        ),
    ]
