# Generated by Django 5.1.6 on 2026-09-11 06:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0100_payroll_accrual_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceMcpClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('client_type', models.CharField(choices=[('public', 'Публичный клиент с PKCE')], default='public', max_length=20)),
                ('redirect_uris', models.JSONField(default=list)),
                ('client_metadata_sha256', models.CharField(max_length=64)),
                ('client_metadata_verified_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceMcpPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceMcpGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopes', models.JSONField(default=list)),
                ('resource', models.CharField(max_length=500)),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=300)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_finance_mcp_grants', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='pool_service.financemcpclient')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='pool_service.financemcpprincipal')),
            ],
            options={
                'ordering': ['-authorized_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='financemcpclient',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oauth_clients', to='pool_service.financemcpprincipal'),
        ),
        migrations.CreateModel(
            name='FinanceMcpAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('organization_ids', models.JSONField(default=list)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('group_by', models.CharField(blank=True, max_length=64)),
                ('result', models.CharField(choices=[('success', 'Успех'), ('denied', 'Отклонено'), ('error', 'Ошибка')], max_length=16)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('response_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='pool_service.financemcpgrant')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='pool_service.financemcpprincipal')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceMcpPrincipalOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_finance_mcp_organization_scopes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_mcp_principal_scopes', to='pool_service.organization')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_scopes', to='pool_service.financemcpprincipal')),
            ],
            options={
                'ordering': ['principal_id', 'organization_id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceMcpRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('family_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('scopes', models.JSONField(default=list)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='pool_service.financemcpgrant')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='pool_service.financemcprefreshtoken')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceMcpAuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('redirect_uri', models.CharField(max_length=1000)),
                ('resource', models.CharField(max_length=500)),
                ('scopes', models.JSONField(default=list)),
                ('code_challenge', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_codes', to='pool_service.financemcpgrant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['expires_at', 'used_at'], name='fin_mcp_code_exp_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinanceMcpAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('audience', models.CharField(max_length=500)),
                ('scopes', models.JSONField(default=list)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='pool_service.financemcpgrant')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
                'indexes': [models.Index(fields=['expires_at', 'revoked_at'], name='fin_mcp_access_exp_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='financemcpgrant',
            index=models.Index(fields=['client', 'revoked_at'], name='fin_mcp_grant_client_idx'),
        ),
        migrations.AddIndex(
            model_name='financemcpgrant',
            index=models.Index(fields=['principal', 'revoked_at'], name='fin_mcp_grant_principal_idx'),
        ),
        migrations.AddIndex(
            model_name='financemcpauditevent',
            index=models.Index(fields=['principal', 'created_at'], name='fin_mcp_audit_principal_idx'),
        ),
        migrations.AddIndex(
            model_name='financemcpauditevent',
            index=models.Index(fields=['tool_name', 'created_at'], name='fin_mcp_audit_tool_idx'),
        ),
        migrations.AddConstraint(
            model_name='financemcpprincipalorganization',
            constraint=models.UniqueConstraint(fields=('principal', 'organization'), name='unique_finance_mcp_principal_org'),
        ),
        migrations.AddIndex(
            model_name='financemcprefreshtoken',
            index=models.Index(fields=['family_id', 'revoked_at'], name='fin_mcp_refresh_family_idx'),
        ),
        migrations.AddIndex(
            model_name='financemcprefreshtoken',
            index=models.Index(fields=['expires_at', 'used_at'], name='fin_mcp_refresh_exp_idx'),
        ),
    ]
