# Generated by Django 5.1.6 on 2026-09-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0107_employee_hr_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeCompensationMonth",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_month", models.DateField()),
                ("percent_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("bonus_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("extra_days_count", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("extra_days_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("transport_compensation_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("deduction_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="compensation_months", to="pool_service.employee")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="employee_compensation_months", to="pool_service.organization")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_employee_compensation_months", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-period_month", "employee_id"],
                "indexes": [models.Index(fields=["organization", "period_month"], name="emp_comp_org_month_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("organization", "employee", "period_month"), name="unique_employee_comp_month"),
                    models.CheckConstraint(condition=models.Q(("percent_amount__gte", 0)), name="emp_comp_percent_nonneg"),
                    models.CheckConstraint(condition=models.Q(("bonus_amount__gte", 0)), name="emp_comp_bonus_nonneg"),
                    models.CheckConstraint(condition=models.Q(("extra_days_count__gte", 0)), name="emp_comp_days_nonneg"),
                    models.CheckConstraint(condition=models.Q(("extra_days_amount__gte", 0)), name="emp_comp_days_amount_nonneg"),
                    models.CheckConstraint(condition=models.Q(("transport_compensation_amount__gte", 0)), name="emp_comp_transport_nonneg"),
                    models.CheckConstraint(condition=models.Q(("deduction_amount__gte", 0)), name="emp_comp_deduction_nonneg"),
                ],
            },
        ),
    ]
