# Generated by Django 5.1.6 on 2026-09-27 06:42

import django.db.models.deletion
import pool_service.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0109_employee_test_rewards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("limits", "limits"),
                    ("missed_visit", "missed_visit"),
                    ("daily_missing", "daily_missing"),
                    ("new_company", "new_company"),
                    ("new_personal", "new_personal"),
                    ("task_assignment", "task_assignment"),
                    ("finance", "finance"),
                    ("development", "development"),
                    ("communication", "communication"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="CommunicationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("avito", "Авито"),
                            ("website", "Сайт"),
                            ("megafon", "Мегафон"),
                        ],
                        max_length=24,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_channels",
                        to="pool_service.organization",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_view_conversations", "Can view conversations"),
                    ("can_reply_conversations", "Can reply to conversations"),
                    ("can_take_conversation", "Can take a conversation"),
                    ("can_assign_conversation", "Can assign a conversation"),
                    ("can_view_all_calls", "Can view all calls"),
                    ("can_view_own_calls", "Can view own calls"),
                    ("can_listen_calls", "Can listen to call recordings"),
                    ("can_manage_channels", "Can manage communication channels"),
                ],
                "unique_together": {("organization", "kind", "name")},
            },
        ),
        migrations.CreateModel(
            name="ChannelConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("external_id", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Non-secret connection metadata only",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="pool_service.communicationchannel",
                    ),
                ),
            ],
            options={
                "unique_together": {("channel", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("participant_name", models.CharField(max_length=255)),
                ("participant_phone", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новое"),
                            ("active", "В работе"),
                            ("waiting", "Ожидаем клиента"),
                            ("done", "Завершено"),
                            ("spam", "Спам / Нецелевое"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversations",
                        to="pool_service.channelconnection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="pool_service.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at", "-created_at"],
                "unique_together": {("connection", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="ConversationAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversation_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversation_assignment_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_history",
                        to="pool_service.conversation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConversationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=255)),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Входящее"), ("out", "Исходящее")], max_length=3
                    ),
                ),
                ("body", models.TextField(blank=True)),
                ("sender_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="pool_service.conversation",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversation_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original",
                    models.FileField(
                        storage=pool_service.storage.PrivateMediaStorage(),
                        upload_to="communications/original/%Y/%m/",
                    ),
                ),
                (
                    "optimized",
                    models.FileField(
                        blank=True,
                        storage=pool_service.storage.PrivateMediaStorage(),
                        upload_to="communications/optimized/%Y/%m/",
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("original_size", models.PositiveBigIntegerField(default=0)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="pool_service.conversationmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhoneCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("phone_number", models.CharField(max_length=40)),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Входящий"), ("out", "Исходящий")], max_length=3
                    ),
                ),
                ("started_at", models.DateTimeField(db_index=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "result",
                    models.CharField(
                        choices=[("answered", "Отвечен"), ("missed", "Пропущен")],
                        max_length=20,
                    ),
                ),
                ("recording_ref", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_calls",
                        to="pool_service.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CallAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transcript", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("facts", models.JSONField(blank=True, default=dict)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="pool_service.phonecall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TelephonyConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Мегафон", max_length=120)),
                ("external_id", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telephony_connections",
                        to="pool_service.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "external_id")},
            },
        ),
        migrations.AddField(
            model_name="phonecall",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="calls",
                to="pool_service.telephonyconnection",
            ),
        ),
        migrations.CreateModel(
            name="WebsiteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(blank=True, max_length=255)),
                ("delivery", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("comment", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField()),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_request",
                        to="pool_service.conversation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConversationReadState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_states",
                        to="pool_service.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_read_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("conversation", "user")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="phonecall",
            unique_together={("connection", "external_id")},
        ),
    ]
