# Generated by Django 5.1.6 on 2026-09-27 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0111_website_communication_api"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvitoCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id_encrypted", models.TextField(editable=False)),
                ("client_secret_encrypted", models.TextField(editable=False)),
                (
                    "access_token_encrypted",
                    models.TextField(blank=True, editable=False),
                ),
                (
                    "access_token_expires_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avito_credential",
                        to="pool_service.channelconnection",
                    ),
                ),
            ],
        ),
    ]
