# Generated by Django 5.1.6 on 2026-09-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0112_avitocredential"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationmessage",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("received", "Получено"),
                    ("pending", "Ожидает отправки"),
                    ("sending", "Отправляется"),
                    ("delivered", "Доставлено"),
                    ("failed", "Ошибка"),
                ],
                default="received",
                max_length=16,
            ),
        ),
    ]
