# Generated by Django 5.1.6 on 2026-09-27 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_communication_access(apps, schema_editor):
    OrganizationAccess = apps.get_model("pool_service", "OrganizationAccess")
    CommunicationAccess = apps.get_model("pool_service", "CommunicationAccess")
    roles_by_pair = {}
    for access in OrganizationAccess.objects.all().iterator():
        roles_by_pair.setdefault((access.organization_id, access.user_id), set()).add(access.role)
    rows = []
    for (organization_id, user_id), roles in roles_by_pair.items():
        values = {}
        if roles & {"owner", "admin"}:
            values = {
                "can_view_conversations": True,
                "can_reply_conversations": True,
                "can_take_conversation": True,
                "can_assign_conversation": True,
                "can_view_all_calls": True,
                "can_view_own_calls": True,
                "can_listen_calls": True,
                "can_manage_channels": True,
            }
        elif "manager" in roles:
            values = {
                "can_view_conversations": True,
                "can_reply_conversations": True,
                "can_take_conversation": True,
                "can_view_own_calls": True,
                "can_listen_calls": True,
            }
        rows.append(CommunicationAccess(
            organization_id=organization_id,
            user_id=user_id,
            **values,
        ))
    CommunicationAccess.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0113_alter_conversationmessage_delivery_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="telephonyconnection",
            name="recording_allowed_hosts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="HTTPS hostnames allowed for recording redirects",
            ),
        ),
        migrations.CreateModel(
            name="CommunicationAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_view_conversations", models.BooleanField(default=False)),
                ("can_reply_conversations", models.BooleanField(default=False)),
                ("can_take_conversation", models.BooleanField(default=False)),
                ("can_assign_conversation", models.BooleanField(default=False)),
                ("can_view_all_calls", models.BooleanField(default=False)),
                ("can_view_own_calls", models.BooleanField(default=False)),
                ("can_listen_calls", models.BooleanField(default=False)),
                ("can_manage_channels", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_accesses",
                        to="pool_service.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "user"),
                        name="comm_access_org_user_uniq",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_communication_access, migrations.RunPython.noop),
    ]
