# Generated by Django 5.1.6 on 2026-09-28

from django.db import migrations, models


def blank_external_ids_to_null(apps, schema_editor):
    ConversationMessage = apps.get_model("pool_service", "ConversationMessage")
    ConversationMessage.objects.filter(external_id="").update(external_id=None)


def null_external_ids_to_blank(apps, schema_editor):
    ConversationMessage = apps.get_model("pool_service", "ConversationMessage")
    ConversationMessage.objects.filter(external_id__isnull=True).update(external_id="")


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0114_telephonyconnection_recording_allowed_hosts_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conversationmessage",
            name="comm_message_external_uniq",
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(
            blank_external_ids_to_null,
            null_external_ids_to_blank,
        ),
        migrations.AddConstraint(
            model_name="conversationmessage",
            constraint=models.UniqueConstraint(
                fields=("conversation", "external_id"),
                name="comm_message_external_uniq",
            ),
        ),
        migrations.AddField(
            model_name="conversationmessage",
            name="delivery_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
