# Generated by Django 5.1 for Service2 reward order workspace.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0116_backfill_communication_access"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OneCCustomerIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("onec_customer_id", models.CharField(max_length=120)),
                ("raw_name", models.CharField(blank=True, max_length=500)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="onec_customer_identities", to="pool_service.client")),
                ("confirmed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="confirmed_onec_customers", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="onec_customer_identities", to="pool_service.organization")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["organization", "client"], name="onec_customer_org_client_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("organization", "onec_customer_id"), name="unique_onec_customer_per_org"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RewardOrderObjectLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_document_key", models.CharField(max_length=255)),
                ("linked_at", models.DateTimeField(auto_now=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reward_order_object_links", to="pool_service.client")),
                ("linked_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="linked_reward_order_objects", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reward_order_object_links", to="pool_service.organization")),
                ("pool", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reward_order_object_links", to="pool_service.pool")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["organization", "pool"], name="reward_order_pool_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("organization", "source_document_key"), name="unique_reward_order_object_link"),
                ],
            },
        ),
    ]
