from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0119_reward_customer_manager_rule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OneCMoneyForecastSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_at", models.DateTimeField()),
                ("fetched_at", models.DateTimeField()),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="money_forecast_snapshots", to="pool_service.organization")),
                ("sync_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="money_forecast_snapshots", to="pool_service.onecodatasyncrun")),
            ],
            options={"ordering": ["-source_at", "-id"]},
        ),
        migrations.CreateModel(
            name="ManagementMoneyPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("direction", models.CharField(choices=[("receipt", "Поступление"), ("payment", "Платёж")], max_length=12)),
                ("source_type", models.CharField(choices=[("order", "Заказ/договор"), ("service", "Сезонное обслуживание"), ("payment", "Прочее обязательство"), ("owner", "Согласованная выплата собственнику"), ("tax", "Налог"), ("payroll", "Зарплата"), ("rent", "Аренда"), ("loan", "Кредит")], max_length=16)),
                ("linked_order_guid", models.UUIDField(blank=True, null=True)),
                ("counterparty_name", models.CharField(blank=True, max_length=300)),
                ("order_reference", models.CharField(blank=True, max_length=160)),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("contractual_due_date", models.DateField(blank=True, null=True)),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("expected_month", models.DateField(blank=True, null=True)),
                ("date_precision", models.CharField(choices=[("exact", "Точная дата"), ("month", "Месяц"), ("unknown", "Дата не назначена")], max_length=12)),
                ("basis", models.CharField(max_length=300)),
                ("confirmation_status", models.CharField(choices=[("confirmed", "Подтверждено"), ("review", "Требует проверки"), ("possible", "Возможная продажа"), ("excluded", "Не входит в прогноз")], default="confirmed", max_length=16)),
                ("note", models.TextField(blank=True)),
                ("service_period_start", models.DateField(blank=True, null=True)),
                ("service_period_end", models.DateField(blank=True, null=True)),
                ("service_active_months", models.JSONField(blank=True, default=list)),
                ("service_payment_offset_months", models.SmallIntegerField(blank=True, null=True)),
                ("service_price_rule", models.CharField(blank=True, max_length=300)),
                ("service_exceptions", models.JSONField(blank=True, default=list)),
                ("price_effective_from", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_management_money_plans", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="management_money_plans", to="pool_service.organization")),
                ("pool", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="money_plans", to="pool_service.pool")),
                ("updated_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="updated_management_money_plans", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["expected_date", "expected_month", "id"]},
        ),
        migrations.CreateModel(
            name="OneCMoneyForecastRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("direction", models.CharField(choices=[("receipt", "Поступление"), ("payment", "Платёж")], max_length=12)),
                ("item_kind", models.CharField(choices=[("order_schedule", "График оплаты заказа покупателя"), ("order_due", "Срок оплаты заказа покупателя"), ("supplier_schedule", "График оплаты заказа поставщику")], max_length=32)),
                ("source_identity", models.CharField(max_length=96)),
                ("order_guid", models.UUIDField(blank=True, null=True)),
                ("agreement_guid", models.UUIDField(blank=True, null=True)),
                ("counterparty_guid", models.UUIDField(blank=True, null=True)),
                ("counterparty_name", models.CharField(blank=True, max_length=300)),
                ("order_number", models.CharField(blank=True, max_length=80)),
                ("order_date", models.DateField(blank=True, null=True)),
                ("order_state", models.CharField(blank=True, max_length=120)),
                ("object_name", models.CharField(blank=True, max_length=300)),
                ("responsible_name", models.CharField(blank=True, max_length=300)),
                ("expected_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("matched_paid_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("remaining_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("payment_match_status", models.CharField(default="not_checked", max_length=32)),
                ("contractual_due_date", models.DateField(blank=True, null=True)),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("expected_month", models.DateField(blank=True, null=True)),
                ("date_precision", models.CharField(choices=[("exact", "Точная дата"), ("month", "Месяц"), ("unknown", "Дата не назначена")], default="unknown", max_length=12)),
                ("basis", models.CharField(blank=True, max_length=300)),
                ("confirmation_status", models.CharField(choices=[("confirmed", "Подтверждено"), ("review", "Требует проверки"), ("possible", "Возможная продажа"), ("excluded", "Не входит в прогноз")], default="review", max_length=16)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("source_payload", models.JSONField(blank=True, default=dict)),
                ("snapshot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rows", to="pool_service.onecmoneyforecastsnapshot")),
            ],
            options={"ordering": ["expected_date", "expected_month", "counterparty_name", "order_number", "id"]},
        ),
        migrations.CreateModel(
            name="ManagementMoneyPlanChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="management_money_plan_changes", to=settings.AUTH_USER_MODEL)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="changes", to="pool_service.managementmoneyplan")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddIndex(model_name="onecmoneyforecastsnapshot", index=models.Index(fields=["organization", "is_active"], name="money_fc_org_active_idx")),
        migrations.AddIndex(model_name="onecmoneyforecastsnapshot", index=models.Index(fields=["organization", "source_at"], name="money_fc_org_time_idx")),
        migrations.AddConstraint(model_name="onecmoneyforecastrow", constraint=models.UniqueConstraint(fields=("snapshot", "source_identity"), name="money_fc_snapshot_identity_uq")),
        migrations.AddIndex(model_name="onecmoneyforecastrow", index=models.Index(fields=["snapshot", "direction", "confirmation_status"], name="money_fc_dir_status_idx")),
        migrations.AddIndex(model_name="onecmoneyforecastrow", index=models.Index(fields=["snapshot", "expected_month"], name="money_fc_month_idx")),
        migrations.AddIndex(model_name="onecmoneyforecastrow", index=models.Index(fields=["snapshot", "order_guid"], name="money_fc_order_idx")),
        migrations.AddIndex(model_name="managementmoneyplan", index=models.Index(fields=["organization", "is_active", "direction"], name="money_plan_org_dir_idx")),
        migrations.AddIndex(model_name="managementmoneyplan", index=models.Index(fields=["organization", "linked_order_guid"], name="money_plan_order_idx")),
        migrations.AddIndex(model_name="managementmoneyplan", index=models.Index(fields=["organization", "expected_month"], name="money_plan_month_idx")),
        migrations.AddIndex(model_name="managementmoneyplanchange", index=models.Index(fields=["plan", "created_at"], name="money_plan_change_idx")),
    ]
