# Generated by Django 5.1.6 on 2026-10-04

import pool_service.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0121_money_forecast_realization_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonecall",
            name="recording_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="phonecall",
            name="recording_downloaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phonecall",
            name="recording_error",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="phonecall",
            name="recording_file",
            field=models.FileField(
                blank=True,
                storage=pool_service.storage.PrivateMediaStorage(),
                upload_to="communications/call_recordings/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="phonecall",
            name="recording_last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phonecall",
            name="recording_status",
            field=models.CharField(
                choices=[
                    ("none", "Нет записи"),
                    ("pending", "Ожидает сохранения"),
                    ("stored", "Сохранена"),
                    ("failed", "Ошибка сохранения"),
                ],
                default="none",
                max_length=16,
            ),
        ),
    ]
