# Generated by Django 5.1.6 on 2026-10-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pool_service", "0122_phonecall_recording_storage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeonecidentity",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeonecidentity",
            name="source_active",
            field=models.BooleanField(
                default=False,
                help_text="Активность записи сотрудника в исходной 1С.",
            ),
        ),
        migrations.CreateModel(
            name="TelephonyEmployeeIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_name", models.CharField(blank=True, max_length=500)),
                (
                    "normalized_name",
                    models.CharField(blank=True, db_index=True, max_length=500),
                ),
                ("extension", models.CharField(max_length=64)),
                ("external_user", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_manual_confirmation", models.BooleanField(default=False)),
                ("reassignment_detected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("auto_matched", "Сопоставлен автоматически"),
                            ("manually_matched", "Сопоставлен вручную"),
                            ("needs_mapping", "Требует сопоставления"),
                            ("excluded", "Исключён"),
                        ],
                        default="needs_mapping",
                        max_length=24,
                    ),
                ),
                (
                    "match_method",
                    models.CharField(
                        choices=[
                            ("exact_name", "Точное ФИО"),
                            ("extension", "Внутренний номер"),
                            ("manual", "Вручную"),
                            ("none", "Нет сопоставления"),
                        ],
                        default="none",
                        max_length=24,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_telephony_employee_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_identities",
                        to="pool_service.telephonyconnection",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telephony_identities",
                        to="pool_service.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telephony_employee_identities",
                        to="pool_service.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["raw_name", "extension", "id"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="tel_emp_org_status_idx",
                    ),
                    models.Index(
                        fields=["connection", "external_user"],
                        name="tel_emp_conn_user_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("connection", "extension"),
                        name="telephony_employee_connection_ext_uniq",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="phonecall",
            name="employee_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="phone_calls",
                to="pool_service.employee",
            ),
        ),
        migrations.AddField(
            model_name="phonecall",
            name="provider_extension",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="phonecall",
            name="provider_user",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
