# Generated by Django 5.1.6 on 2026-10-08 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0131_phonecall_internal_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOwnedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('pool', 'Бассейн'), ('irrigation', 'Автополив'), ('hammam', 'Хамам'), ('water', 'Водоподготовка')], max_length=16)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('parameters', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_objects', to='pool_service.client')),
            ],
            options={
                'ordering': ['object_type', 'name', 'id'],
            },
        ),
    ]
