# Generated by Django 5.1.6 on 2026-10-08 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0132_clientownedobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoApiThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('next_allowed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
