# Generated by Django 5.1.6 on 2026-10-08 12:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0133_avito_api_throttle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoStatusMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('generation', models.UUIDField(default=uuid.uuid4)),
                ('baseline_at', models.DateTimeField(blank=True, null=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_item_count', models.PositiveIntegerField(default=0)),
                ('last_page_count', models.PositiveIntegerField(default=0)),
                ('next_due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_monitor', to='pool_service.channelconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool_service.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvitoListingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=16)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='pool_service.avitostatusmonitor')),
            ],
        ),
        migrations.AddIndex(
            model_name='avitostatusmonitor',
            index=models.Index(fields=['enabled', 'next_due_at'], name='avito_monitor_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='avitolistingstatus',
            constraint=models.UniqueConstraint(fields=('monitor', 'item_id'), name='avito_monitor_item_uniq'),
        ),
    ]
