# Generated by Django 5.1.6 on 2026-10-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_service', '0137_call_processing_usage_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoSchedulerHeartbeat',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('run_id', models.UUIDField()),
                ('state', models.CharField(max_length=16)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
                ('exit_code', models.IntegerField(null=True)),
            ],
        ),
    ]
